### ISSUE TITLE
Present AlertView before state changes

### ISSUE THREAD

**Issue by moh-abk** [bfeher/BFPaperCheckbox#4]
Hi,

I'm trying to present an AlertView before the below method is called;

    - (void)paperCheckboxChangedState:(BFPaperCheckbox *)checkbox

And based on the button clicked in the alertview I decide whether to call the above method or not.
Is it possible?

Thanks.

**Comment by bfeher** [comment]
I'm sorry but I don't quite understand your issue. Why not just call `checkAnimated:(BOOL)animated` or `uncheckAnimated:(BOOL)animated` after your AlertView closes?
